from .xcolor import Color

# 默认风格
xcolor_black1 = Color("black1")
xcolor_red1 = Color("red1")
xcolor_green1 = Color("green1")
xcolor_yellow1 = Color("yellow1")
xcolor_blue1 = Color("blue1")
xcolor_magenta1 = Color("magenta1")
xcolor_cyan1 = Color("cyan1")
xcolor_white1 = Color("white1")

xcolor_black2 = Color("black2")
xcolor_red2 = Color("red2")
xcolor_green2 = Color("green2")
xcolor_yellow2 = Color("yellow2")
xcolor_blue2 = Color("blue2")
xcolor_magenta2 = Color("magenta2")
xcolor_cyan2 = Color("cyan2")
xcolor_white2 = Color("white2")

# 斜体风格
xcolor_iblack1  = Color("black1", "italic")
xcolor_ired1 = Color("red1", "italic")
xcolor_igreen1 = Color("green1", "italic")
xcolor_iyellow1 = Color("yellow1", "italic")
xcolor_iblue1 = Color("blue1", "italic")
xcolor_imagenta1 = Color("magenta1", "italic")
xcolor_icyan1 = Color("cyan1", "italic")
xcolor_iwhite1 = Color("white1", "italic")

xcolor_iblack2 = Color("black2", "italic")
xcolor_ired2 = Color("red2", "italic")
xcolor_igreen2 = Color("green2", "italic")
xcolor_iyellow2 = Color("yellow2", "italic")
xcolor_iblue2 = Color("blue2", "italic")
xcolor_imagenta2 = Color("magenta2", "italic")
xcolor_icyan2 = Color("cyan2", "italic")
xcolor_iwhite2 = Color("white2", "italic")

# 下划线风格
xcolor_ublack1  = Color("black1", "underline")
xcolor_ured1 = Color("red1", "underline")
xcolor_ugreen1 = Color("green1", "underline")
xcolor_uyellow1 = Color("yellow1", "underline")
xcolor_ublue1 = Color("blue1", "underline")
xcolor_umagenta1 = Color("magenta1", "underline")
xcolor_ucyan1 = Color("cyan1", "underline")
xcolor_uwhite1 = Color("white1", "underline")

xcolor_ublack2 = Color("black2", "underline")
xcolor_ured2 = Color("red2", "underline")
xcolor_ugreen2 = Color("green2", "underline")
xcolor_uyellow2 = Color("yellow2", "underline")
xcolor_ublue2 = Color("blue2", "underline")
xcolor_umagenta2 = Color("magenta2", "underline")
xcolor_ucyan2 = Color("cyan2", "underline")
xcolor_uwhite2 = Color("white2", "underline")

# 删除线风格
xcolor_tblack1  = Color("black1", "throughline")
xcolor_tred1 = Color("red1", "throughline")
xcolor_tgreen1 = Color("green1", "throughline")
xcolor_tyellow1 = Color("yellow1", "throughline")
xcolor_tblue1 = Color("blue1", "throughline")
xcolor_tmagenta1 = Color("magenta1", "throughline")
xcolor_tcyan1 = Color("cyan1", "throughline")
xcolor_twhite1 = Color("white1", "throughline")

xcolor_tblack2 = Color("black2", "throughline")
xcolor_tred2 = Color("red2", "throughline")
xcolor_tgreen2 = Color("green2", "throughline")
xcolor_tyellow2 = Color("yellow2", "throughline")
xcolor_tblue2 = Color("blue2", "throughline")
xcolor_tmagenta2 = Color("magenta2", "throughline")
xcolor_tcyan2 = Color("cyan2", "throughline")
xcolor_twhite2 = Color("white2", "throughline")

# 闪烁风格
xcolor_fblack1  = Color("black1", "flash")
xcolor_fred1 = Color("red1", "flash")
xcolor_fgreen1 = Color("green1", "flash")
xcolor_fyellow1 = Color("yellow1", "flash")
xcolor_fblue1 = Color("blue1", "flash")
xcolor_fmagenta1 = Color("magenta1", "flash")
xcolor_fcyan1 = Color("cyan1", "flash")
xcolor_fwhite1 = Color("white1", "flash")

xcolor_fblack2 = Color("black2", "flash")
xcolor_fred2 = Color("red2", "flash")
xcolor_fgreen2 = Color("green2", "flash")
xcolor_fyellow2 = Color("yellow2", "flash")
xcolor_fblue2 = Color("blue2", "flash")
xcolor_fmagenta2 = Color("magenta2", "flash")
xcolor_fcyan2 = Color("cyan2", "flash")
xcolor_fwhite2 = Color("white2", "flash")

# 加粗风格
xcolor_bblack = Color("black1", "bold")
xcolor_bred = Color("red1", "bold")
xcolor_bgreen = Color("green1", "bold")
xcolor_byellow = Color("yellow1", "bold")
xcolor_bblue = Color("blue1", "bold")
xcolor_bmagenta = Color("magenta1", "bold")
xcolor_bcyan = Color("cyan1", "bold")
xcolor_bwhite = Color("white1", "bold")
