from .xcolor import Color

# 默认风格
black1 = Color("black1")
red1 = Color("red1")
green1 = Color("green1")
yellow1 = Color("yellow1")
blue1 = Color("blue1")
magenta1 = Color("magenta1")
cyan1 = Color("cyan1")
white1 = Color("white1")

black2 = Color("black2")
red2 = Color("red2")
green2 = Color("green2")
yellow2 = Color("yellow2")
blue2 = Color("blue2")
magenta2 = Color("magenta2")
cyan2 = Color("cyan2")
white2 = Color("white2")

# 斜体风格
iblack1  = Color("black1", "italic")
ired1 = Color("red1", "italic")
igreen1 = Color("green1", "italic")
iyellow1 = Color("yellow1", "italic")
iblue1 = Color("blue1", "italic")
imagenta1 = Color("magenta1", "italic")
icyan1 = Color("cyan1", "italic")
iwhite1 = Color("white1", "italic")

iblack2 = Color("black2", "italic")
ired2 = Color("red2", "italic")
igreen2 = Color("green2", "italic")
iyellow2 = Color("yellow2", "italic")
iblue2 = Color("blue2", "italic")
imagenta2 = Color("magenta2", "italic")
icyan2 = Color("cyan2", "italic")
iwhite2 = Color("white2", "italic")

# 下划线风格
ublack1  = Color("black1", "underline")
ured1 = Color("red1", "underline")
ugreen1 = Color("green1", "underline")
uyellow1 = Color("yellow1", "underline")
ublue1 = Color("blue1", "underline")
umagenta1 = Color("magenta1", "underline")
ucyan1 = Color("cyan1", "underline")
uwhite1 = Color("white1", "underline")

ublack2 = Color("black2", "underline")
ured2 = Color("red2", "underline")
ugreen2 = Color("green2", "underline")
uyellow2 = Color("yellow2", "underline")
ublue2 = Color("blue2", "underline")
umagenta2 = Color("magenta2", "underline")
ucyan2 = Color("cyan2", "underline")
uwhite2 = Color("white2", "underline")

# 删除线风格
tblack1  = Color("black1", "throughline")
tred1 = Color("red1", "throughline")
tgreen1 = Color("green1", "throughline")
tyellow1 = Color("yellow1", "throughline")
tblue1 = Color("blue1", "throughline")
tmagenta1 = Color("magenta1", "throughline")
tcyan1 = Color("cyan1", "throughline")
twhite1 = Color("white1", "throughline")

tblack2 = Color("black2", "throughline")
tred2 = Color("red2", "throughline")
tgreen2 = Color("green2", "throughline")
tyellow2 = Color("yellow2", "throughline")
tblue2 = Color("blue2", "throughline")
tmagenta2 = Color("magenta2", "throughline")
tcyan2 = Color("cyan2", "throughline")
twhite2 = Color("white2", "throughline")

# 闪烁风格
fblack1  = Color("black1", "flash")
fred1 = Color("red1", "flash")
fgreen1 = Color("green1", "flash")
fyellow1 = Color("yellow1", "flash")
fblue1 = Color("blue1", "flash")
fmagenta1 = Color("magenta1", "flash")
fcyan1 = Color("cyan1", "flash")
fwhite1 = Color("white1", "flash")

fblack2 = Color("black2", "flash")
fred2 = Color("red2", "flash")
fgreen2 = Color("green2", "flash")
fyellow2 = Color("yellow2", "flash")
fblue2 = Color("blue2", "flash")
fmagenta2 = Color("magenta2", "flash")
fcyan2 = Color("cyan2", "flash")
fwhite2 = Color("white2", "flash")

# 加粗风格
bblack = Color("black1", "bold")
bred = Color("red1", "bold")
bgreen = Color("green1", "bold")
byellow = Color("yellow1", "bold")
bblue = Color("blue1", "bold")
bmagenta = Color("magenta1", "bold")
bcyan = Color("cyan1", "bold")
bwhite = Color("white1", "bold")
